// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1bMrMDsr6wAPWK6zF_UyVroX5iSqDoRc',
    appId: '1:892948304434:web:eef697e4a10ae2009f222b',
    messagingSenderId: '892948304434',
    projectId: 'test-sns-login-d401e',
    authDomain: 'test-sns-login-d401e.firebaseapp.com',
    storageBucket: 'test-sns-login-d401e.appspot.com',
    measurementId: 'G-0YP9EVP5EZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvVWfkkD6WWI9jNo21at1MpwwXIrqb-OE',
    appId: '1:892948304434:android:53c23a5584a963cf9f222b',
    messagingSenderId: '892948304434',
    projectId: 'test-sns-login-d401e',
    storageBucket: 'test-sns-login-d401e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcdevxCDRmwoTvtINVGfG4Sebqpc-BStU',
    appId: '1:892948304434:ios:45c333fc85db43de9f222b',
    messagingSenderId: '892948304434',
    projectId: 'test-sns-login-d401e',
    storageBucket: 'test-sns-login-d401e.appspot.com',
    androidClientId: '892948304434-8vnr3lk2nu7pkhanjj2fv4ltrgvabpq8.apps.googleusercontent.com',
    iosClientId: '892948304434-1kis35kutoihntc7nb3ovrtvufasqsi3.apps.googleusercontent.com',
    iosBundleId: 'com.leonamin.cuteshrew.flutterFirebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcdevxCDRmwoTvtINVGfG4Sebqpc-BStU',
    appId: '1:892948304434:ios:45c333fc85db43de9f222b',
    messagingSenderId: '892948304434',
    projectId: 'test-sns-login-d401e',
    storageBucket: 'test-sns-login-d401e.appspot.com',
    androidClientId: '892948304434-8vnr3lk2nu7pkhanjj2fv4ltrgvabpq8.apps.googleusercontent.com',
    iosClientId: '892948304434-1kis35kutoihntc7nb3ovrtvufasqsi3.apps.googleusercontent.com',
    iosBundleId: 'com.leonamin.cuteshrew.flutterFirebaseAuthentication',
  );
}
